### ISSUE TITLE
mvapich device is not contained in `src/include/Rules.mk` leading to undefined ESMF_FC

### ISSUE THREAD

**Issue by platipodium** [schism-dev/schism-esmf#13]
In `src/include/Rules.mk` we consider openmpi, mpich2, mpich3 and intelmpi devices, but not yet mvapich2.  This is available and can be tested on femto.

**Comment by platipodium** [comment]
There is also a problem in the script with path splitting with `-`

/sciclone/home20/clemmen/devel/schism/schism-esmf% mpifort -compile_info  | cut -d' ' -f1 | cut -d'-' -f1
/usr/local/intel

**Comment by platipodium** [comment]
Fixed by commit e4a0d9b

**Comment by josephzhang8** [comment]
Thx Carsten! I'll need to look at the schism_step(it) carefully after I go back from the conference. It'd not be a problem to make it INT8, which I think is integer(kind=8) in FORT? I'm surprised that this would crash the code..


-Joseph

Joseph Zhang
Office: (804) 684 7466
Web: schism.wiki

**Comment by platipodium** [comment]
> Thx Carsten! I'll need to look at the schism_step(it) carefully after I go back from the conference. It'd not be a problem to make it INT8, which I think is integer(kind=8) in FORT? I'm surprised that this would crash the code..
> […](#)

Your comment is directed to #15.  And there is no crash, as we limit the I8 datatype coming from ESMF to max out (and exit beyond) I4 limit.
