### ISSUE TITLE
Compiling issue with gfortran

### ISSUE THREAD

**Issue by danishyo** [schism-dev/schism-esmf#18]
Test with 1c586a6, ESMF 8.3.0.

The following are compiliing errors:

./libschism_esmf.a(lap.F90.o): In function `dswap_':
lap.F90:(.text+0x0): multiple definition of `dswap_'
./lib/libblas.a(dswap.o):dswap.f:(.text+0x0): first defined here
./libschism_esmf.a(lap.F90.o): In function `ddot_':
lap.F90:(.text+0x180): multiple definition of `ddot_'
./lib/libblas.a(ddot.o):ddot.f:(.text+0x0): first defined here
./libschism_esmf.a(lap.F90.o): In function `dcopy_':
lap.F90:(.text+0x370): multiple definition of `dcopy_'
./lib/libblas.a(dcopy.o):dcopy.f:(.text+0x0): first defined here
./libschism_esmf.a(lap.F90.o): In function `lsame_':
lap.F90:(.text+0x5a0): multiple definition of `lsame_'
./lib/liblapack.a(lsame.o):lsame.f:(.text+0x0): first defined here
./libschism_esmf.a(lap.F90.o): In function `dscal_':
lap.F90:(.text+0xcf0): multiple definition of `dscal_'
./lib/libblas.a(dscal.o):dscal.f:(.text+0x0): first defined here
./libschism_esmf.a(lap.F90.o): In function `idamax_':
lap.F90:(.text+0x1170): multiple definition of `idamax_'
./lib/libblas.a(idamax.o):idamax.f:(.text+0x0): first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:117: schism_pdaf] Error 1

**Comment by platipodium** [comment]
Is a Duplikat of #17
