### ISSUE TITLE
Try "ESMF_TimeSetString" for line 1622, but get "undefined reference error".

### ISSUE THREAD

**Issue by platipodium** [schism-dev/schism-esmf#9]
(reported by @danishyo )

The code can only be successfully compile after modifying the following in schism_esmf_util.F90,

Comment line 1622 and uncomment 1620& 1621 to instead, I try "ESMF_TimeSetString" for line 1622, but get "undefined reference error".

**Comment by platipodium** [comment]
```
! Set day as timestep temporarily to count later to stop time
  !call ESMF_TimeSet(startTime, yy=start_year, mm=start_month, dd=start_day, &
  !  h=start_hour, rc=localrc)
  call ESMF_TimeSet(startTime, trim(message), rc=localrc)
  _SCHISM_LOG_AND_FINALIZE_ON_ERROR_(rc_)
```

**Comment by platipodium** [comment]
`ESMF_TimeSetString`  is the private name of the public interface `ESMF_TimeSet(time, timestring, rc)`.

**Comment by platipodium** [comment]
I cannot reproduce the problem @danishyo 

 * schism f0daa03
 * schism_esmf  b1ac7cf

Compiles fine on femto ESMF_8_3_0_beta_snapshot_06-14-g9f69d90 and strand ESMF_8_3_0_beta_snapshot_06

**Comment by danishyo** [comment]
I check again and confirm this problem only happen with ESMF_8_0_1.
Compiling with ESMF_8_1_0 & ESMF_8_2_0 won't cause the problem.
